config/routes.rb
Rails.application.routes.draw do
  resources :contributions, expect: [:show, :new, :edit]

  root 'contributions#index'

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
    validates :contributor, presence: true, length: { maximum: 15}
    validates :email, allow_blank: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, length: { maximum: 50}
    validates :text, presence: true, length: { maximum: 1000 } 

    paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contributions_controller.rb
# encoding: UTF-8
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  # GET /contributions
  # GET /contributions.json
  def index
    @contributions = Contribution.order("id DESC").page params[:page]

    @contribution = Contribution.new
    @contribution.contributor = session[:contributor] if session[:contributor]
    @contribution.email = session[:email] if session[:email]
  end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # GET /contributions/1/edit
  def edit
  end

  # POST /contributions
  # POST /contributions.json
  def create
    @contribution = Contribution.new(contribution_params)
    session[:contributor] = @contribution.contributor
    session[:email] = @contribution.email

    respond_to do |format|
      if @contribution.save
        format.html { redirect_to contributions_url, notice: '投稿しました' }
        format.json { render :index, status: :created, location: @contribution }
      else
        @contributions = Contribution.order("id DESC").page params[:page]
        format.html { render :index }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to contributions_url, notice: '編集しました' }
        format.json { render :show, status: :ok, location: @contribution }
      else
        format.html { render :edit }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to contributions_url, notice: '投稿を削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contribution_params
      params.require(:contribution).permit(:text, :contributor, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_form.html.erb
# encoding: UTF-8
<%= form_for(@contribution) do |f| %>
  <% if @contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contribution.errors.count, "error") %> 入力項目に誤りがあります</h2>

      <ul>
      <% @contribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contributor %>:
    <%= f.text_field :contributor, :placeholder => "名前", :maxlength => 15 %>
    <%= f.label :email %>:
    <%= f.text_field :email, :placeholder => "mail@example.com", :maxlength => 50 %>
  </div>
  <div class="field">
    <%= f.text_area :text, :size => "70x5", :maxlength => 1000 %>
  </div>
  <div class="actions">
    <%= f.submit :data => {:disable_with => "保存中..."} %>
  </div>
<% end %>

app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form' %>

<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<h1><%= t('view.title') %></h1>

<%= render 'form' %>

<p id="notice"><%= notice %></p>

<div>
  <span id="more-paginate"><%= paginate @contributions %></span>
</div>

<table class="contributions-table">
  <tbody>
    <% @contributions.each do |contribution| %>
      <tr>
        <td>
          <span class="contribution-id"><%= contribution.id %></span>
          <span class="contributor"><%= contribution.contributor %></span>
        </td>
        <td><%= contribution.email %></td>
        <td><%= l(contribution.created_at, format: :long) %></td>
      </tr>
      <tr>
        <td colspan=3><%= simple_format(h(contribution.text)) %></td>
      </tr>
      <tr>
        <td colspan=3><hr></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <span id="more-paginate"><%= paginate @contributions %></span>
</div>

app/views/contributions/index.js.erb
$("#contributions").append("<%= escape_javascript(
    render 'contributions', object: @contributions
) %>")

$("#more_link").replaceWith("<%= escape_javascript(
    link_to_next_page(@contributions, 'more', remote: true, id: 'more_link')
) %>");

app/views/contributions/new.html.erb
<h1>入力項目が不正です</h1>

<%= render 'form' %>

<%= link_to 'Back', contributions_path %>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @contribution.text %>
</p>

<p>
  <strong>Contributor:</strong>
  <%= @contribution.contributor %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contribution.email %>
</p>

<%= link_to 'Edit', edit_contribution_path(@contribution) %> |
<%= link_to 'Back', contributions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>